import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI } from "@google/genai";
import dotenv from "dotenv";

// Load environment variables
dotenv.config();

const app = express();
const PORT = 3000;

app.use(express.json({ limit: "50mb" }));

// Initialize Gemini SDK lazily to avoid crashing on startup if key is missing
let aiClient: GoogleGenAI | null = null;

function getAiClient(): GoogleGenAI {
  if (!aiClient) {
    const key = process.env.GEMINI_API_KEY;
    if (!key) {
      throw new Error("GEMINI_API_KEY is not configured in your environment. Please add it via Settings > Secrets.");
    }
    aiClient = new GoogleGenAI({
      apiKey: key,
      httpOptions: {
        headers: {
          "User-Agent": "aistudio-build",
        }
      }
    });
  }
  return aiClient;
}

// REST API for AI Business Analysis
app.post("/api/ai/analyze", async (req, res) => {
  const { type, data } = req.body;
  
  if (!type || !data) {
    return res.status(400).json({ success: false, error: "Missing 'type' or 'data' in request body." });
  }

  try {
    const ai = getAiClient();
    
    let systemInstruction = "You are an expert Chartered Accountant, Indian GST consultant, and Business Growth strategist for Indian small businesses. Write a professional, highly readable report in markdown format. Be direct, clear, action-oriented, and structured with elegant headers.";
    
    let prompt = "";
    const serializedData = JSON.stringify(data, null, 2);

    switch (type) {
      case "sales":
        prompt = `Analyze the following sales history and provide a detailed Sales Analysis report.\n\nSales Data:\n${serializedData}\n\nTasks:\n1. Provide a scannable summary of total sales and average transaction size.\n2. Identify top customers and active days.\n3. Identify sales trends and seasonal patterns if observable.\n4. Recommend 3 concrete strategies to boost sales.`;
        break;
      case "profit":
        prompt = `Analyze the following financial summary (Sales, Purchases, Expenses) and provide a Profit & Loss analysis.\n\nFinancial Data:\n${serializedData}\n\nTasks:\n1. Calculate Gross Profit, Net Profit, and Operating Profit Margin.\n2. Detail the cost breakdown (Purchase vs Expenses).\n3. Recommend 3 concrete cost reduction or margin expansion tactics tailored to these numbers.`;
        break;
      case "stock":
        prompt = `Analyze the current product catalog and stock levels, and provide Stock & Reorder Suggestions.\n\nProduct & Stock Data:\n${serializedData}\n\nTasks:\n1. Identify products that are low or out of stock.\n2. Calculate inventory valuation and highlight which category holds the most value.\n3. Predict reorder requirements based on stock trends.\n4. Highlight any potential dead stock.`;
        break;
      case "tips":
        prompt = `Analyze this general business profile (Company Details, active metrics) and provide 5 Actionable Business growth tips.\n\nBusiness Info:\n${serializedData}\n\nTasks:\n1. Suggest optimized GST compliance and credit practices (e.g. ITC utilization).\n2. Detail working capital optimization tips (how to collect receivables faster).\n3. Provide local market expansion strategies for Indian retailers/wholesalers.`;
        break;
      case "summary":
        prompt = `Analyze this comprehensive ERP business state and provide an executive business summary.\n\nState Summary:\n${serializedData}\n\nTasks:\n1. Create an Executive Summary outlining the business health (excellent, warning, critical).\n2. Highlight key critical actions (e.g. taxes to pay, unpaid bills, low stock alert).\n3. Present a SWOT style assessment in simple bullet points.`;
        break;
      default:
        prompt = `Analyze the following business metrics and provide professional insights.\n\nData:\n${serializedData}`;
    }

    const response = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: prompt,
      config: {
        systemInstruction,
        temperature: 0.7,
      }
    });

    const reportText = response.text || "No response text generated by AI.";
    res.json({ success: true, report: reportText });

  } catch (error: any) {
    console.error("AI Analysis Error:", error);
    res.status(500).json({ 
      success: false, 
      error: error?.message || "Internal server error during AI analysis. Is the Gemini API key active and correct?" 
    });
  }
});

// Setup Vite Dev server middleware or static distribution folders
async function setupServer() {
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`PCS Billing Pro AI server is running on http://0.0.0.0:${PORT}`);
  });
}

setupServer();
